# Generated by Django 5.1.4 on 2024-12-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('orden', models.IntegerField(verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
                'db_table': 'Paginas',
                'ordering': ['id'],
            },
        ),
    ]
