# Generated by Django 5.1.4 on 2024-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
